// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: protobuf/import/computer.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Computer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Cpu    *CPU    `protobuf:"bytes,2,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory *Memory `protobuf:"bytes,3,opt,name=memory,proto3" json:"memory,omitempty"`
}

func (x *Computer) Reset() {
	*x = Computer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_import_computer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Computer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Computer) ProtoMessage() {}

func (x *Computer) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_import_computer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Computer.ProtoReflect.Descriptor instead.
func (*Computer) Descriptor() ([]byte, []int) {
	return file_protobuf_import_computer_proto_rawDescGZIP(), []int{0}
}

func (x *Computer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Computer) GetCpu() *CPU {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *Computer) GetMemory() *Memory {
	if x != nil {
		return x.Memory
	}
	return nil
}

var File_protobuf_import_computer_proto protoreflect.FileDescriptor

var file_protobuf_import_computer_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x69, 0x6d, 0x70, 0x6f, 0x72,
	0x74, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x06, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x1a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e,
	0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x65, 0x0a, 0x08, 0x43, 0x6f, 0x6d,
	0x70, 0x75, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x03, 0x63, 0x70, 0x75,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x2e,
	0x43, 0x50, 0x55, 0x52, 0x03, 0x63, 0x70, 0x75, 0x12, 0x26, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f,
	0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x69, 0x6d, 0x70, 0x6f, 0x72,
	0x74, 0x2e, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79,
	0x42, 0x17, 0x5a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x69, 0x6d, 0x70,
	0x6f, 0x72, 0x74, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_protobuf_import_computer_proto_rawDescOnce sync.Once
	file_protobuf_import_computer_proto_rawDescData = file_protobuf_import_computer_proto_rawDesc
)

func file_protobuf_import_computer_proto_rawDescGZIP() []byte {
	file_protobuf_import_computer_proto_rawDescOnce.Do(func() {
		file_protobuf_import_computer_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_import_computer_proto_rawDescData)
	})
	return file_protobuf_import_computer_proto_rawDescData
}

var file_protobuf_import_computer_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protobuf_import_computer_proto_goTypes = []interface{}{
	(*Computer)(nil), // 0: import.Computer
	(*CPU)(nil),      // 1: import.CPU
	(*Memory)(nil),   // 2: import.Memory
}
var file_protobuf_import_computer_proto_depIdxs = []int32{
	1, // 0: import.Computer.cpu:type_name -> import.CPU
	2, // 1: import.Computer.memory:type_name -> import.Memory
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protobuf_import_computer_proto_init() }
func file_protobuf_import_computer_proto_init() {
	if File_protobuf_import_computer_proto != nil {
		return
	}
	file_protobuf_import_component_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_protobuf_import_computer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Computer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_import_computer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_import_computer_proto_goTypes,
		DependencyIndexes: file_protobuf_import_computer_proto_depIdxs,
		MessageInfos:      file_protobuf_import_computer_proto_msgTypes,
	}.Build()
	File_protobuf_import_computer_proto = out.File
	file_protobuf_import_computer_proto_rawDesc = nil
	file_protobuf_import_computer_proto_goTypes = nil
	file_protobuf_import_computer_proto_depIdxs = nil
}
